### ISSUE TITLE
wrong pattern?

### ISSUE THREAD

**Issue by zktuong** [ncborcherding/Ibex#1]
Hi, cool repo(s)! 

Just a minor thing - wondering if this pattern should be `^IG[HKL][VDJ]` instead?
https://github.com/ncborcherding/Ibex/blob/5235eb09b33bc2ce4146ce2a353fc916f89abfb0/R/runIbex.R#L86

**Comment by ncborcherding** [comment]
Nice catch and thanks for letting me know - most recent commit fixes that error. 

Nick
