### ISSUE TITLE
I am not able to install the Ibex on my Macbook M3 computer

### ISSUE THREAD

**Issue by mainyanghr** [ncborcherding/Ibex#4]
library(scRepertoire)
library(Trex)
library(reticulate)
library(tensorflow)
library(keras)

I have already installed the above package, it seems the "bluster" package is needed, which is not available for M3 arm64.  I am wondering whether there is another strategies to install this useful package.

Thank you very much!

Harry

**Comment by ncborcherding** [comment]
Hey Harry, 

As of bioconductor 3.16, there should be support for arm64 (see [here](https://bioconductor.org/news/bioc_3_16_release/)).

Maybe you need to update your BiocManager and then install bluster? 

Nick

**Comment by mainyanghr** [comment]
> Hey Harry,
> 
> As of bioconductor 3.16, there should be support for arm64 (see [here](https://bioconductor.org/news/bioc_3_16_release/)).
> 
> Maybe you need to update your BiocManager and then install bluster?
> 
> Nick

Thank you very much. It is installed finally. Have a nice day!
