### ISSUE TITLE
BCR prediction

### ISSUE THREAD

**Issue by mainyanghr** [ncborcherding/Ibex#5]
Dear Ibex community,

Recently, I am thinking to predict the BCR epitope for human B cells, I am wondering whether Ibex has such functions. If not, I am wondering whether other R package can do the similar things.

Thanks
Harry

**Comment by ncborcherding** [comment]
Hey Harry, 

We haven't including the statistical frameworks for epitope prediction, but you can use the outputs (latent embeddings) to make these predictions using something like the caret library in R. 

I am not aware of any R-based BCR prediction methods - alternatively there are some other pipelines for prediction: 
* [http://tools.iedb.org/main/bcell/](http://tools.iedb.org/main/bcell/)
* [ImmuneML](https://immuneml.uio.no/)

Hope that helps,
Nick
